export const dataOne = [
  { label: 'R1', value: 'R1' },
  { label: 'R2', value: 'R2' },
  { label: 'R3', value: 'R3' },
  { label: 'R4', value: 'R4' },
  { label: 'R5', value: 'R5' },
  { label: 'R6', value: 'R6' },
  { label: 'R7', value: 'R7' },
  { label: 'R8', value: 'R8' },
  { label: 'R9', value: 'R9' },
  { label: 'R10', value: 'R10' },
  { label: 'R11', value: 'R11' },
  { label: 'R12', value: 'R12' },
  { label: 'R13', value: 'R13' },
  { label: 'R14', value: 'R14' },
  { label: 'R15', value: 'R15' },
  { label: 'R16', value: 'R16' },
  { label: 'R17', value: 'R17' },
  { label: 'R18', value: 'R18' },
];

export const dataTwo = [
  { label: 'B1', value: 'B1' },
  { label: 'B2', value: 'B2' },
  { label: 'B3', value: 'B3' },
  { label: 'B4', value: 'B4' },
  { label: 'B5', value: 'B5' },
  { label: 'B6', value: 'B6' },
  { label: 'B7', value: 'B7' },
  { label: 'B8', value: 'B8' },
  { label: 'B9', value: 'B9' },
  { label: 'B1', value: 'B1' },
  { label: 'B2', value: 'B2' },
  { label: 'B3', value: 'B3' },
  { label: 'B4', value: 'B4' },
  { label: 'B5', value: 'B5' },
  { label: 'B6', value: 'B6' },
  { label: 'B7', value: 'B7' },
  { label: 'B8', value: 'B8' },
  { label: 'B9', value: 'B9' },
];

export const dataThree = [
  { label: 'C1', value: 'C1' },
  { label: 'C2', value: 'C2' },
  { label: 'C3', value: 'C3' },
  { label: 'C4', value: 'C4' },
  { label: 'C5', value: 'C5' },
  { label: 'C6', value: 'C6' },
  { label: 'C7', value: 'C7' },
  { label: 'C8', value: 'C8' },
  { label: 'C9', value: 'C9' },
  { label: 'C1', value: 'C1' },
  { label: 'C2', value: 'C2' },
  { label: 'C3', value: 'C3' },
  { label: 'C4', value: 'C4' },
  { label: 'C5', value: 'C5' },
  { label: 'C6', value: 'C6' },
  { label: 'C7', value: 'C7' },
  { label: 'C8', value: 'C8' },
  { label: 'C9', value: 'C9' },
];
