export const dataOne = [
  { label: 'A1', value: 'A1' },
  { label: 'A2', value: 'A2' },
  { label: 'A3', value: 'A3' },
  { label: 'A4', value: 'A4' },
  { label: 'A5', value: 'A5' },
  { label: 'A6', value: 'A6' },
  { label: 'A7', value: 'A7' },
  { label: 'A8', value: 'A8' },
  { label: 'A9', value: 'A9' },
  { label: 'A1', value: 'A1' },
  { label: 'A2', value: 'A2' },
  { label: 'A3', value: 'A3' },
  { label: 'A4', value: 'A4' },
  { label: 'A5', value: 'A5' },
  { label: 'A6', value: 'A6' },
  { label: 'A7', value: 'A7' },
  { label: 'A8', value: 'A8' },
  { label: 'A9', value: 'A9' },
];

export const dataTwo = [
  { label: 'B1', value: 'B1' },
  { label: 'B2', value: 'B2' },
  { label: 'B3', value: 'B3' },
  { label: 'B4', value: 'B4' },
  { label: 'B5', value: 'B5' },
  { label: 'B6', value: 'B6' },
  { label: 'B7', value: 'B7' },
  { label: 'B8', value: 'B8' },
  { label: 'B9', value: 'B9' },
  { label: 'B1', value: 'B1' },
  { label: 'B2', value: 'B2' },
  { label: 'B3', value: 'B3' },
  { label: 'B4', value: 'B4' },
  { label: 'B5', value: 'B5' },
  { label: 'B6', value: 'B6' },
  { label: 'B7', value: 'B7' },
  { label: 'B8', value: 'B8' },
  { label: 'B9', value: 'B9' },
];

export const dataThree = [
  { label: 'C1', value: 'C1' },
  { label: 'C2', value: 'C2' },
  { label: 'C3', value: 'C3' },
  { label: 'C4', value: 'C4' },
  { label: 'C5', value: 'C5' },
  { label: 'C6', value: 'C6' },
  { label: 'C7', value: 'C7' },
  { label: 'C8', value: 'C8' },
  { label: 'C9', value: 'C9' },
  { label: 'C1', value: 'C1' },
  { label: 'C2', value: 'C2' },
  { label: 'C3', value: 'C3' },
  { label: 'C4', value: 'C4' },
  { label: 'C5', value: 'C5' },
  { label: 'C6', value: 'C6' },
  { label: 'C7', value: 'C7' },
  { label: 'C8', value: 'C8' },
  { label: 'C9', value: 'C9' },
];
